# Generated by Django 2.0.1 on 2018-05-12 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='date et heure')),
                ('justifiee', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='AnneeCourante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dateDebutSemestre1', models.DateTimeField(verbose_name='date début semestre 1')),
                ('dateDebutSemestre2', models.DateTimeField(verbose_name='date début semestre 2')),
                ('dateFinSemestre1', models.DateTimeField(verbose_name='date fin semestre 1')),
                ('dateFinSemestre2', models.DateTimeField(verbose_name='date fin semestre 2')),
                ('dateDebutOptions1', models.DateTimeField(verbose_name='date début options semestre 1')),
                ('dateDebutOptions2', models.DateTimeField(verbose_name='date début options semestre 2')),
                ('dateFinOptions1', models.DateTimeField(verbose_name='date fin options semestre 1')),
                ('dateFinOptions2', models.DateTimeField(verbose_name='date fin options semestre 2')),
                ('dateDebutAnnee', models.DateTimeField(verbose_name='date début année')),
                ('dateFinAnnee', models.DateTimeField(verbose_name='date fin année')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20)),
                ('ajac', models.BooleanField(default='False')),
                ('redoublant', models.BooleanField(default='False')),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_par_UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionnelle', models.BooleanField(default='False')),
                ('groupe', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('choisie', models.BooleanField(default='False')),
                ('valide', models.BooleanField(default='True')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('a_choisir_dans_pole', models.IntegerField(default=2)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Pole_par_Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_options', models.IntegerField(default=0)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Pole')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur_par_UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuresCM', models.IntegerField(default=0)),
                ('heuresTP', models.IntegerField(default=0)),
                ('heuresTD', models.IntegerField(default=0)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('diminutif', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nombre_heures', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypePole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('num_UE', models.CharField(max_length=200)),
                ('code_apoge', models.CharField(max_length=200)),
                ('nombre_groupes', models.IntegerField(default=0)),
                ('nombre_heures_TD', models.IntegerField(default=0)),
                ('nombre_heures_CM', models.IntegerField(default=0)),
                ('capacite', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='UE_par_Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.BooleanField(default='False')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Pole')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.UE')),
            ],
        ),
        migrations.AddField(
            model_name='ue',
            name='poles',
            field=models.ManyToManyField(through='optionnelles.UE_par_Pole', to='optionnelles.Pole'),
        ),
        migrations.AddField(
            model_name='ue',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Semestre'),
        ),
        migrations.AddField(
            model_name='professeur_par_ue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.UE'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Statut'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='ues',
            field=models.ManyToManyField(through='optionnelles.Professeur_par_UE', to='optionnelles.UE'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pole_par_semestre',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Semestre'),
        ),
        migrations.AddField(
            model_name='pole',
            name='semestres',
            field=models.ManyToManyField(through='optionnelles.Pole_par_Semestre', to='optionnelles.Semestre'),
        ),
        migrations.AddField(
            model_name='pole',
            name='typePole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.TypePole'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Promotion'),
        ),
        migrations.AddField(
            model_name='etudiant_par_ue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.UE'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parcours',
            field=models.ManyToManyField(to='optionnelles.Parcours'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ues',
            field=models.ManyToManyField(through='optionnelles.Etudiant_par_UE', to='optionnelles.UE'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anneecourante',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Parcours'),
        ),
        migrations.AddField(
            model_name='absence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.Etudiant'),
        ),
        migrations.AddField(
            model_name='absence',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionnelles.UE'),
        ),
    ]
